#!/usr/bin/env node
/**
 * Reads version + codename from the root package.json and writes
 * typed version modules into each workspace's src/generated/ directory.
 *
 * Outputs:
 *   src/generated/version.ts                    (web)
 *   packages/desktop/src/generated/version.ts   (desktop)
 *
 * Both export: VERSION, CODENAME, VERSION_STRING.
 *
 * Runs before dev, build, and type-check scripts in both workspaces.
 * Generated files are gitignored; regenerating is cheap (<10 ms).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'));

const VERSION = pkg.version;
const CODENAME = pkg.codename;

if (!VERSION || !CODENAME) {
  console.error('generate-version: package.json must have both `version` and `codename`');
  process.exit(1);
}

const VERSION_STRING = `v${VERSION} 🔥 ${CODENAME}`;

const moduleContent = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit.
// Source: root package.json (\`version\` + \`codename\`).

export const VERSION = ${JSON.stringify(VERSION)};
export const CODENAME = ${JSON.stringify(CODENAME)};
export const VERSION_STRING = ${JSON.stringify(VERSION_STRING)};
`;

const targets = [
  join(repoRoot, 'src', 'generated', 'version.ts'),
  join(repoRoot, 'packages', 'desktop', 'src', 'generated', 'version.ts'),
];

for (const target of targets) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, moduleContent);
}

// Service worker: substitute __VERSION__ in the template and write public/sw.js.
// The web app's service worker needs the version baked in at build time for
// cache-busting; templating it keeps the bump scope down to root package.json.
const swTemplate = readFileSync(join(repoRoot, 'public', 'sw.template.js'), 'utf8');
const swOutput = swTemplate.replaceAll('__VERSION__', VERSION);
writeFileSync(join(repoRoot, 'public', 'sw.js'), swOutput);

console.log(`generate-version: wrote ${VERSION_STRING} to ${targets.length} targets + sw.js`);
